// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaLoja.Data;

#nullable disable

namespace MinhaLoja.Migrations
{
    [DbContext(typeof(MinhaLojaDbContext))]
    [Migration("20221113131107_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinhaLoja.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Endereco")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NomePrefixo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NomePrimeiro")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NomeSegundo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NomeSufixo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomePrimeiro = "Cliente A",
                            NomeSufixo = "Ref 1"
                        },
                        new
                        {
                            Id = 2,
                            NomePrimeiro = "Cliente B",
                            NomeSufixo = "Ref 1"
                        },
                        new
                        {
                            Id = 3,
                            NomePrimeiro = "Cliente B",
                            NomeSufixo = "Ref 2"
                        },
                        new
                        {
                            Id = 4,
                            NomePrimeiro = "Cliente C",
                            NomeSufixo = "Ref 1"
                        });
                });

            modelBuilder.Entity("MinhaLoja.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EntregaData")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntregaPrevisaoData")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SinalValor")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            Data = new DateTime(2021, 2, 28, 19, 53, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pedido 01",
                            EntregaData = new DateTime(2021, 3, 3, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            EntregaPrevisaoData = new DateTime(2021, 3, 4, 19, 53, 0, 0, DateTimeKind.Unspecified),
                            Pago = true,
                            ServicoId = 1,
                            SinalValor = 0m,
                            Valor = 15.00m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            Data = new DateTime(2021, 8, 30, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pedido 01",
                            EntregaData = new DateTime(2021, 9, 1, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            EntregaPrevisaoData = new DateTime(2021, 9, 1, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            Pago = true,
                            ServicoId = 1,
                            SinalValor = 0m,
                            Valor = 0.00m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 3,
                            Data = new DateTime(2021, 11, 13, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pedido 01",
                            EntregaData = new DateTime(2021, 11, 12, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            EntregaPrevisaoData = new DateTime(2021, 11, 13, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            Pago = false,
                            ServicoId = 1,
                            SinalValor = 0m,
                            Valor = 7.00m
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 3,
                            Data = new DateTime(2021, 11, 13, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pedido 02",
                            EntregaPrevisaoData = new DateTime(2021, 11, 17, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            Pago = false,
                            ServicoId = 2,
                            SinalValor = 0m,
                            Valor = 10.00m
                        });
                });

            modelBuilder.Entity("MinhaLoja.Models.PedidoEntregaPrevisaoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoEntregaPrevisaoHistoricos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2021, 3, 2, 19, 53, 0, 0, DateTimeKind.Unspecified),
                            PedidoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2021, 11, 13, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            PedidoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2021, 11, 15, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            PedidoId = 4
                        });
                });

            modelBuilder.Entity("MinhaLoja.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Serviço 01",
                            Valor = 15.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Serviço 02",
                            Valor = 10.00m
                        });
                });

            modelBuilder.Entity("MinhaLoja.Models.Pedido", b =>
                {
                    b.HasOne("MinhaLoja.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaLoja.Models.Servico", "Servico")
                        .WithMany("Pedidos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("MinhaLoja.Models.PedidoEntregaPrevisaoHistorico", b =>
                {
                    b.HasOne("MinhaLoja.Models.Pedido", "Pedido")
                        .WithMany("EntregaPrevisaoHistoricos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MinhaLoja.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("MinhaLoja.Models.Pedido", b =>
                {
                    b.Navigation("EntregaPrevisaoHistoricos");
                });

            modelBuilder.Entity("MinhaLoja.Models.Servico", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
